add_rules("mode.debug", "mode.release")

set_languages("cxx17")

add_requires("zlib", "sqlite3")

target("mgit")
    set_kind("binary")
    add_files("src/*.cpp", "src/utils/*.cpp")
    add_includedirs("src/headers", "src/utils", "external")
    add_packages("zlib", "sqlite3")

target("mgit_prod")
    set_kind("binary")
    set_basename("mgit")
    set_targetdir("build/prod")
    add_files("src/*.cpp", "src/utils/*.cpp")
    add_includedirs("src/headers", "src/utils", "external")
    add_packages("zlib", "sqlite3")
    set_optimize("fastest")
    set_strip("all")
    set_symbols("hidden")
    add_defines("NDEBUG")
    add_cxflags("-flto", "-fomit-frame-pointer", "-ffunction-sections",
                "-fdata-sections", "-march=native", "-mtune=native",
                {force = true})
    add_ldflags("-flto", "-Wl,--gc-sections", {force = true})

target("integration_cli_test")
    set_kind("binary")
    add_files("tests/integration_cli_test.cpp")
    set_languages("cxx17")
    add_deps("mgit")

target("test")
    set_kind("phony")
    add_deps("mgit", "integration_cli_test")
    on_run(function ()
        import("core.project.project")
        local mgit = project.target("mgit"):targetfile()
        local itest = project.target("integration_cli_test"):targetfile()
        os.execv(itest, {mgit})
        os.execv("bash", {"tests/smoke_cli.sh", mgit})
    end)

target("compile-test")
    set_kind("phony")
    add_deps("mgit", "integration_cli_test")
    on_run(function ()
        import("core.project.project")
        local mgit = project.target("mgit"):targetfile()
        local itest = project.target("integration_cli_test"):targetfile()
        os.execv(itest, {mgit})
        os.execv("bash", {"tests/smoke_cli.sh", mgit})
    end)

target("prod")
    set_kind("phony")
    add_deps("mgit_prod")
    on_run(function ()
        cprint("${bright green}Production binary ready:${clear} build/prod/mgit")
    end)
