add_rules("mode.debug", "mode.release")

set_languages("cxx17")

add_requires("zlib", "sqlite3")

target("mgit")
    set_kind("binary")
    add_files("src/*.cpp", "src/utils/*.cpp")
    add_includedirs("src/headers", "src/utils", "external")
    add_packages("zlib", "sqlite3")

target("integration_cli_test")
    set_kind("binary")
    add_files("tests/integration_cli_test.cpp")
    set_languages("cxx17")
    add_deps("mgit")

target("test")
    set_kind("phony")
    add_deps("mgit", "integration_cli_test")
    on_run(function ()
        import("core.project.project")
        local mgit = project.target("mgit"):targetfile()
        local itest = project.target("integration_cli_test"):targetfile()
        os.execv(itest, {mgit})
        os.execv("bash", {"tests/smoke_cli.sh", mgit})
    end)

target("compile-test")
    set_kind("phony")
    add_deps("mgit", "integration_cli_test")
    on_run(function ()
        import("core.project.project")
        local mgit = project.target("mgit"):targetfile()
        local itest = project.target("integration_cli_test"):targetfile()
        os.execv(itest, {mgit})
        os.execv("bash", {"tests/smoke_cli.sh", mgit})
    end)
